name: Staging


on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  deploy:
    name: "Staging"
    runs-on: self-hosted
    env:
      enableLocalPublishingTest: 'false'
      gradleArgs: --scan "-Dorg.gradle.jvmargs=-Xmx2048m" "-Dfile.encoding=UTF-8" --no-daemon "-Porg.gradle.parallel=false"
      isMac: ${{ startsWith(matrix.os, 'macos') }}
      isWindows: ${{ startsWith(matrix.os, 'windows') }}
      isUbuntu: ${{ startsWith(matrix.os, 'ubuntu') }}
      isUnix: ${{ startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu') }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - if: ${{ env.isUnix == 'true' }}
        run: chmod -R +x *

      - name: Check
        run: ./gradlew clean check ${{ env.gradleArgs }}

      - name: Install
        run: ./gradlew installDist ${{ env.gradleArgs }}

      - run: rm -rf build

      - run: docker ps -a -q --filter ancestor=solvo-platform --format="{{.ID}}" >> oldContainers.txt
      - run: docker image prune --force
      - run: docker build -t solvo-platform .
      - run: docker rm $(docker stop $(cat oldContainers.txt)) || true
      - run: docker run --env PORT=80 --publish 0.0.0.0:80:80/tcp --detach solvo-platform
